image: docker:19.03.10

services:
  - docker:dind

variables:
  AWS_REGION: "ap-southeast-1" 
  REPOSITORY_URL: aws_account_id.dkr.ecr.ap-southeast-1.amazonaws.com/pyapp
  IMAGE_TAG: $CI_COMMIT_REF_NAME

before_script:
  - apk add --no-cache python3 py3-pip jq  # Install necessary tools
  - pip3 install --upgrade awscli
  # Debugging: Print environment variables to ensure they are set correctly
  - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
  - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
  - echo "AWS_REGION=$AWS_REGION"
  # Set AWS CLI configuration
  - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
  - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
  - aws configure set region "$AWS_REGION"

stages:
  - build
  - deploy
  
build:
  stage: build
  when: manual
  script:
    - $(aws ecr get-login --no-include-email --region "$AWS_REGION")
    - docker build -t $REPOSITORY_URL:$IMAGE_TAG  .
    - docker push $REPOSITORY_URL:$IMAGE_TAG
  only:
    - master

deploy:
  stage: deploy
  when: manual
  before_script:
    # Install SSH agent
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    # Add SSH key stored in GitLab CI/CD variables
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Disable strict host key checking for SSH
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    # Run script on the EC2 instance
    - ssh ubuntu@your-ec2-public-ip -t "cd /home/ubuntu && bash deploy.sh"

after_script:
  - docker logout $REPOSITORY_URL

